# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master-Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build:ci
    - name: Test
      run: npm run test:ci
    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_DENTAL_HOST_THEME }}
        BRANCH: gh-pages
        FOLDER: dist/dental-host-theme

#    - name: Archive code coverage result
#      if: success()
#      uses: actions/upload-artifact@v1
#      with:
#        name: deploy_coverage
#        path: coverage

# DEPLOY MANUEL STEPS
# ng build --prod --base-href "https://mengineer59.github.io/dental-host-theme/"
# npx angular-cli-ghpages --dir=dist/dental-host-theme